# Generated by Django 2.0.7 on 2018-07-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.CharField(help_text='Enter the id of computer', max_length=20, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of computer', max_digits=10)),
                ('date_of_purchase', models.DateField(auto_now_add=True, help_text='Enter the date of purchase')),
                ('status', models.CharField(choices=[('WK', 'Working'), ('OO', 'Out of Order'), ('IM', 'In Maintenance')], default='WK', max_length=2)),
            ],
        ),
    ]
