# Generated by Django 2.0.7 on 2018-07-17 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date(2018, 7, 17), help_text='Enter the date of purchase'),
        ),
    ]
