# Generated by Django 2.0.7 on 2018-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180717_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
