# Generated by Django 2.0.7 on 2018-07-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180717_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the item', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('name', models.OneToOneField(help_text='Pick the Store Item Name', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='inventory.StoreItemName')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Enter the quantity of Store Item')),
                ('last_modified', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
