# Generated by Django 2.0.7 on 2018-07-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storeitem_storeitemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
