# Generated by Django 2.0.7 on 2018-07-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180722_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(help_text='Select room where it is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room'),
        ),
    ]
