# Generated by Django 2.0.7 on 2018-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180817_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='serial_no',
            field=models.CharField(help_text='Enter the serial number of the item', max_length=50, null='True', unique=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='serial_no',
            field=models.CharField(help_text='Enter the serial number of the item', max_length=50, null='True', unique=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='no_of_SFP_ports',
            field=models.PositiveSmallIntegerField(default=4, help_text='Enter the number of SFP ports'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='serial_no',
            field=models.CharField(help_text='Enter the serial number of the item', max_length=50, null='True', unique=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.100', help_text='Enter the ip address for this printer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='serial_no',
            field=models.CharField(help_text='Enter the serial number of the item', max_length=50, null='True', unique=True),
        ),
    ]
